### ISSUE TITLE
Safe mode on widget click

### ISSUE THREAD

**Issue by L4Hacks** [ryannair05/Cylinder-Reborn#2]
iPX ios 14.3 Odysseyrain (libhooker) crashes on widget click. Only cylinder installed

**Comment by StrugglingDoge** [comment]
Can confirm, I have an iPhone 12 Pro on iOS 14.3 using Unc0ver 6.0.0(Substitute) and am having the same issue.

Attempting to tap on any widget instantly sends my device into safe mode.

**Comment by neoighodaro** [comment]
Same here. Disabled till then

**Comment by ryannair05** [comment]
Fixed in Version 1.0.2

**Comment by L4Hacks** [comment]
It’s fixed, but: I have lynx installed, and if I hide labels (widgets labels) it still crashes (only when opening /closing and app and sliding fast to the next page). Could you investigate this?
